development:
  adapter: redis
  url: redis://localhost:6379

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:ce5331a71d87d0437cf4449a7f7cd218@spinyfin.redistogo.com:11733/
